### ISSUE TITLE
Bito text area doesn't accept any chars

### ISSUE THREAD

**Issue by cgunkan** [gitbito/bitoai#104] opened 2023-07-02 14:40 UTC
cloned from https://github.com/gitbito/bitoai/issues/25

 I downloaded the latest version from the marketplace, 
 Unfortunately, i have still typing issue.. 
 ENTER/ESC/TAB , they are working but textbox doesn't show any chars, however, copy and paste works fine.
 
 ENV : 
OS: Centos 7, 

GoLand 2021.3.4
Build #GO-213.7172.22, built on March 15, 2022
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 3.10.0-1160.49.1.el7.x86_64
GC: G1 Young Generation, G1 Old Generation

**Comment by bitomukesh** [comment] 2023-07-05 14:39
Hi, this is a known issue and we are fixing it soon.

**Comment by nisha-bito** [comment] 2023-07-19 11:45
hi @cgunkan ,

Can you please install the latest version of Bito 1.1.2 from marketplace and check if the issue is resolved for you ? 

Thanks,
Nisha

**Comment by nisha-bito** [comment] 2023-08-04 05:22
hi @cgunkan ,

Reported issue is resolved with Bito 1.1.2 release. This ticket will be closed now. In case you come across any further issue, feel free to create a new issue. 

Thanks,
Nisha

**Closed by nisha-bito** 2023-08-04 05:22 UTC
