### ISSUE TITLE
Generated Python code has invalid indentation

### ISSUE THREAD

**Issue by GuiLuan** [gitbito/bitoai#78] opened 2023-06-04 03:03 UTC
Hello, I'm experiencing an issue in my latest version of VS Code (with the latest version of Bitoai's extensions installed). 
![image](https://github.com/gitbito/bitoai/assets/100982603/8e561744-7b30-47d9-a1a2-80a7605e80c4)
As you can see in the screenshot below, there is always an extra indentation before the def keyword in my code.

**Comment by bitoandy** [comment] 2023-06-04 17:09
Hi @GuiLuan ,

We are looking into this issue on our end and will provide an update once the issue is resolved.

**Comment by nisha-bito** [comment] 2023-06-30 17:38
Hi @GuiLuan ,

Version 1.1.1 is available in marketplace. Please download and check if this has resolved reported issue. 

Thanks,
Nisha

**Comment by nisha-bito** [comment] 2023-07-20 12:35
hi @GuiLuan ,

Version 1.1.2 is also available in marketplace. Please download and check if this has resolved reported issue.
Please note, this ticket will be auto closed in few days, please feel free to create a new ticket in case the problem still exists. 

Thanks,
Nisha

**Closed** 2023-08-04 07:58 UTC
