### ISSUE TITLE
Garbled characters appear in the Enable Auto Completion function

### ISSUE THREAD

**Issue by SMSshuai** [gitbito/bitoai#168] opened 2023-11-20 00:59 UTC
When the “Enable Auto Completion”function is used, garbled characters appear in Chinese and the Chinese code is UTF-8
![image](https://github.com/gitbito/bitoai/assets/66891829/fdc1194f-001a-443f-a6af-6e75548f4c22)

**Comment by bitoandy** [comment] 2023-11-20 01:01
Thanks @SMSshuai for reporting this. We are looking into this and will keep you posted on the update.

**Comment by nisha-bito** [comment] 2023-11-27 16:23
hi @SMSshuai ,

The fix  for above issue is released along with Bito 1.2.6. Please install the new version and let us know if this is working fine for you.

Thanks,
Nisha

**Comment by SMSshuai** [comment] 2023-11-28 01:09
> hi @SMSshuai ,
> 
> The fix for above issue is released along with Bito 1.2.6. Please install the new version and let us know if this is working fine for you.
> 
> Thanks, Nisha

sorry,my experience time is up and I can't help you test this problem.

**Comment by nisha-bito** [comment] 2023-11-28 07:26
hi @SMSshuai ,

Can you please help us with you email which you are using for Bito. I would provide you more Code completion requests so that you can use it for again. 

Thanks,
nisha

**Comment by SMSshuai** [comment] 2023-11-28 07:32
> 你好@SMSshuai,
> 
> 您可以帮助我们处理您用于 Bito 的电子邮件吗？我会为您提供更多代码完成请求，以便您可以再次使用它。
> 
> 谢谢， 妮莎

ok~319115175@qq.com

**Comment by nisha-bito** [comment] 2023-11-28 11:57
hi @SMSshuai ,

We have provided more Code completion requests to you. You can use it until the quota expires again.
Please do test the reported issue and let us know if this is still coming for you ?

Thanks,
nisha

**Comment by SMSshuai** [comment] 2023-11-29 01:50
Code auto-complete doesn't work, it doesn't pop up on its own, I'm not sure if it conflicts with other plugins, I've installed a lot of plugins recently. I tried to uninstall the newly installed plugin, but it still couldn't be used. I also triggered by "Ait+Shift+k", also using the official case, but it still couldn't solve the problem. The suspicion may be a similar feature conflict with github copilot (although I uninstalled it).
![QQ截图20231129094927](https://github.com/gitbito/bitoai/assets/66891829/b899dd5d-4743-4ef3-8336-ddd96d0bc588)

**Comment by SMSshuai** [comment] 2023-11-29 01:53
> 你好@SMSshuai,
> 
> 我们已向您提供了更多代码完成请求。您可以使用它，直到配额再次到期。 请测试所报告的问题，并让我们知道您是否仍然遇到此问题？
> 
> 谢谢， 妮莎

Code auto-complete doesn't work, it doesn't pop up on its own, I'm not sure if it conflicts with other plugins, I've installed a lot of plugins recently. I tried to uninstall the newly installed plugin, but it still couldn't be used. I also triggered by "Ait+Shift+k", also using the official case, but it still couldn't solve the problem. The suspicion may be a similar feature conflict with github copilot (although I uninstalled it).
If I have time in the next few days, I will try to operate this account on other computers. I will give feedback if there is any problem, thank you.
![QQ截图20231129094927](https://github.com/gitbito/bitoai/assets/66891829/967953d5-1241-4694-84e6-995d95a300d7)

**Comment by nisha-bito** [comment] 2023-11-29 17:18
hi @SMSshuai ,

We will look into it.

Thanks,
Nisha

**Comment by SMSshuai** [comment] 2023-12-02 11:08
> @SMSshuai ,
> 
> We have added some fix for this. Can you please try today and let us know if this is still happening for you.
> 
> Thanks, Nisha

All IDEA encoding Settings are UTF-8, and the file encoding is also UTF-8 version, which is the freshest 1.2.5

**Comment by nisha-bito** [comment] 2023-12-21 17:41
hi @SMSshuai ,

Please download Bito 1.2.6. This issue should not come in latest version of Bito. 

Thanks,
nisha

**Comment by nisha-bito** [comment] 2023-12-28 17:33
hi @SMSshuai ,

We have done multiple optimisation with our latest release 1.2.7 release. This issue should not come in latest version of Bito.
Please let us know in case you still see this issue at your end. 

Thanks,
Nisha

**Comment by nisha-bito** [comment] 2024-01-08 11:04
hi @SMSshuai ,

Gentle reminder to confirm if the issue is resolved in latest version of Bito 1.2.7?
Please note: the issue will be closed after 7 days. You can always create a new issue or re-open this again. 

Thanks
Nisha

**Closed** 2024-02-12 18:08 UTC
