### ISSUE TITLE
When I scroll through the Bito Docs pages, there is jittering that occurs.

### ISSUE THREAD

**Issue by monicfenga** [gitbito/bitoai#15] opened 2023-03-17 10:40 UTC
For example [this page](https://docs.bito.ai/bito-ai-examples)

When scrolling, note the scroll bar on the right hand side, which has a strange jittering effect when scrolling, and if you scroll the page with the Page Down or direction down keys, you may see the jitter directly on the page.

I find this very strange.

https://user-images.githubusercontent.com/39868412/226084615-76bf5627-cb92-495e-bac4-a79278e768db.mp4

**Comment by nisha-bito** [comment] 2023-03-17 21:23
hi @monicfenga 
Can you please confirm the Bito version you are using along with the IDE and OS details. This will help us analyze the issue better.

**Comment by monicfenga** [comment] 2023-03-17 22:56
> hi @monicfenga Can you please confirm the Bito version you are using along with the IDE and OS details. This will help us analyze the issue better.
> 
> Thanks, Nisha

Web browser: A Chromium based browser, Chromium version: 86.0.4240.198
visits this page: https://docs.bito.ai/bito-ai-examples

Bito AI in my editor is perfectly fine in scrolling.

Extension version: 1.0.131
VS Code version: 1.74.3
OS version: Windows 10 (1809)

**Comment by bitoandy** [comment] 2023-03-18 04:18
Hi @monicfenga ,

We just updated the marketplace with 1.0.132 build, fixing some of these issue. Can you update to the latest build and let us know if the issue is resolved?

**Comment by monicfenga** [comment] 2023-03-18 04:36
OK, I'll give it a try(a day or two or so), it will take some time. I will let you know if there are any unusual happenings.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月18日(星期六) 中午12:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gitbito/bitoai] When I scroll through the Bito Docs pages, there is jittering that occurs. (Issue #15)





 
Hi @monicfenga ,
 
We just updated the marketplace with 1.0.132 build, fixing some of these issue. Can you update to the latest build and let us know if the issue is resolved?
 
&mdash;

**Comment by bitoandy** [comment] 2023-03-19 18:16
Thanks @monicfenga

**Comment by bitomukesh** [comment] 2023-03-21 06:37
Hi, we have hosted our doc site on Gitbook. Let us check why the scrolling is not smooth. There are instances where certain web app scrolling could be jittery if the hardware acceleration is enabled in Chrome.  We will check and let you know.

**Comment by bitomukesh** [comment] 2023-08-16 04:46
Closing this for now. We may move to different doc platform that integrates support with documentation.

**Closed by bitomukesh** 2023-08-16 04:46 UTC
