### ISSUE TITLE
Bito v1.2.3 can not work with IDEA 2021.2.3

### ISSUE THREAD

**Issue by Lori888** [gitbito/bitoai#162] opened 2023-11-09 06:14 UTC
com.intellij.diagnostic.PluginException: Cannot load class co.bito.intellij.actions.InsertCodeIntoBito (
  error: co/bito/intellij/actions/InsertCodeIntoBito has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 55.0,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=ChatGPT GPT-4 - Bito AI Code Assistant, id=co.bito.bito-intellij, descriptorPath=plugin.xml, path=...\bin\IdeaConfig\config\plugins\Bito-Jetbrains-PROD, version=1.2.3, package=null), packagePrefix=null, instanceId=273, state=active)
)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:409)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:256)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1489)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:887)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:195)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:180)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:518)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:507)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:381)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:341)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:320)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doGetChildren(ActionUpdater.java:602)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$1(ActionUpdater.java:114)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:176)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$2(ActionUpdater.java:114)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$getGroupChildren$26(ActionUpdater.java:411)
	at com.intellij.util.TimeoutUtil.compute(TimeoutUtil.java:134)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$getGroupChildren$28(ActionUpdater.java:410)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.getGroupChildren(ActionUpdater.java:409)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.iterateGroupChildren(ActionUpdater.java:556)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:440)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$23(ActionUpdater.java:402)
	at com.intellij.util.TimeoutUtil.compute(TimeoutUtil.java:134)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$25(ActionUpdater.java:401)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1483)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:401)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:230)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$14(ActionUpdater.java:281)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$16(ActionUpdater.java:305)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$17(ActionUpdater.java:305)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$18(ActionUpdater.java:301)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:270)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$19(ActionUpdater.java:300)
	at com.intellij.codeWithMe.ClientId$Companion.withClientId(ClientId.kt:135)
	at com.intellij.codeWithMe.ClientId.withClientId(ClientId.kt)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$20(ActionUpdater.java:298)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.UnsupportedClassVersionError: co/bito/intellij/actions/InsertCodeIntoBito has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass2(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1109)
	at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:290)
	at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:121)
	at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:55)
	at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:217)
	at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:176)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:401)
	... 56 more

**Comment by nisha-bito** [comment] 2023-11-09 11:13
hi @Lori888 ,

We will look into it. 
You can downgrade the version to previous Bito version 1.1.10 int he mean time to continue using Bito. use link to download older version of Bito.
https://plugins.jetbrains.com/plugin/18289-chatgpt-gpt-4--bito-ai-code-assistant/edit/versions/stable/429874

Thanks,
nisha

**Comment by barryzpc** [comment] 2023-11-10 02:21
I had the same problem with IDEA 2021.2

**Comment by cs916830023** [comment] 2023-11-10 09:06
I had the same problem with IntelliJ IDEA 2022.1.3

**Comment by Lori888** [comment] 2023-11-10 09:11
Bito v1.2.3 can work with IDEA 2023.2.4

**Comment by cs916830023** [comment] 2023-11-10 09:15
> Bito v1.2.3 can work with IDEA 2023.2.4

What version of java are you using?

**Comment by cs916830023** [comment] 2023-11-10 09:17
> hi @cs916830023 ,
> 
> Can you upgrade to Java 15 and try again ?
> 
> Thanks, nisha

nb@nbdeMacBook-Pro ~ % java -version
java version "17.0.7" 2023-04-18 LTS
Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.7+8-LTS-224, mixed mode, sharing)

**Comment by cs916830023** [comment] 2023-11-10 09:19
> hi @cs916830023 ,
> 
> Can you upgrade to Java 15 and try again ?
> 
> Thanks, nisha

Do I have to use Java 15?

**Comment by Lori888** [comment] 2023-11-10 09:20
@cs916830023

I'm using JDK11:
java version "11.0.11" 2021-04-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.11+9-LTS-194)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.11+9-LTS-194, mixed mode)

**Comment by SMSshuai** [comment] 2023-11-14 02:06
> hi @cs916830023 ,
> 
> Can you upgrade to Java 15 and try again ?
> 
> Thanks, nisha

This error also occurs in JDK17

**Comment by cs916830023** [comment] 2023-11-14 02:32
> hi @cs916830023 ,
> 
> Can you upgrade to Java 15 and try again ?
> 
> Thanks, nisha

I cannot change to jdk15, because my project and other software need jdk17, and I have downgraded the use of bito

**Comment by nisha-bito** [comment] 2023-11-14 14:33
hi @barryzpc , @cs916830023 , @Lori888 , @SMSshuai , @barryzpc ,

We will be releasing a fix soon for the issue, in the mean time you can downgrade the version to previous Bito version 1.1.10 int he mean time to continue using Bito. use link to download older version of Bito.
https://plugins.jetbrains.com/plugin/18289-chatgpt-gpt-4--bito-ai-code-assistant/edit/versions/stable/429874

Thanks,
Nisha

**Comment by bitoandy** [comment] 2023-11-14 22:12
Hi All,
We are working on the update which should hit the JetBrains marketplace over the weekend or early next week with a fix for this issue.

**Comment by nisha-bito** [comment] 2023-11-16 15:52
hi @barryzpc , @cs916830023 , @Lori888 , @SMSshuai , @barryzpc ,

Bito version 1.2.4 is available now on marketplace, can you upgrade and let us know if the issue is resolved now ? 

Thanks,
Nisha

**Comment by SMSshuai** [comment] 2023-11-17 00:53
> hi @barryzpc , @cs916830023 , @Lori888 , @SMSshuai , @barryzpc ,
> 
> Bito version 1.2.4 is available now on marketplace, can you upgrade and let us know if the issue is resolved now ?
> 
> Thanks, Nisha

It's working fine and the new features are great

**Comment by nisha-bito** [comment] 2023-11-17 11:34
Great to hear, thanks !!!

**Closed by nisha-bito** 2023-11-17 11:34 UTC

**Comment by barryzpc** [comment] 2023-11-20 07:12
> hi @barryzpc , @cs916830023 , @Lori888 , @SMSshuai , @barryzpc ,
> 
> Bito version 1.2.4 is available now on marketplace, can you upgrade and let us know if the issue is resolved now ?
> 
> Thanks, Nisha

It worked fine with my IDEA2021.2, thank you

**Comment by cs916830023** [comment] 2023-11-20 08:13
Bito 1.2.4 is already available on my IDEA,thanks.
