### ISSUE TITLE
cannot input korean language

### ISSUE THREAD

**Issue by mahomi** [gitbito/bitoai#127] opened 2023-08-09 08:34 UTC
I cannot input korean language. I am using windows 10 and Intellij lastest version.

**Comment by bitoandy** [comment] 2023-08-09 19:11
Thanks @mahomi for reporting this. We are looking into this and will keep you posted.

**Comment by nisha-bito** [comment] 2023-08-16 15:57
hi @mahomi ,

Can you please confirm the Bito version you are using ? 

Thanks,
Nisha

**Comment by nisha-bito** [comment] 2023-10-19 12:47
hi @mahomi ,

Please confirm if the issue is resolved for you with latest version of Bito ?
We have some existing new feature avaialable with Bito 1.1.9, please install and use it.

We will be closing this ticket, please feel free to create new ticket if the issue still persists.

Thanks,
Nisha

**Closed by nisha-bito** 2023-10-19 12:47 UTC
Labels: bug
