### ISSUE TITLE
Questions about Bazel projects always result in "Could not find a relevant data or information to answer the question."

### ISSUE THREAD

**Issue by Algomorph** [gitbito/bitoai#198] opened 2024-03-29 13:56 UTC
Questions about Bazel projects always result in "Could not find a relevant data or information to answer the question."
Here's an example session:
https://share.bito.ai/static/share?aid=7dead434-b8ee-40ca-9f05-8ba594934b6e

"Please list all header files in the `/mediapipe/calculators/core/` folder of the current project." should be a trivial task.

Replication: 
This is based on the open-source [mediapipe](https://github.com/google/mediapipe) project, imported into CLion using the [Bazel](https://plugins.jetbrains.com/plugin/9554-bazel-for-clion) plugin. When importing, please copy/paste the contents of the zipped up .bazelproject file (attached).

Version info:
```
CLion 2023.3.4
Build #CL-233.14475.31, built on February 13, 2024
Licensed to Presage Security, Inc / Gregory Kramida
Subscription is active until November 19, 2024.
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.0-26-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 32
Registry:
  debugger.attach.dialog.enabled=true
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
Non-Bundled Plugins:
  idea.plugin.protoeditor (233.13135.65)
  dev.meanmail.plugin.nginx-intellij-plugin (2022.1.1)
  A move tab left and right using the keyboard plugin - by momomo.com (12.550)
  co.bito.bito-intellij (1.3.0)
  com.mikejhill.intellij.movetab (2.1.1)
  ru.adelf.idea.dotenv (2024.1)
  kemoke.net.cssmodule (1.1)
  com.haulmont.rcb (233.13135.65)
  com.google.idea.bazel.clwb (2024.03.12.0.1-api-version-233)
Current Desktop: ubuntu:GNOME
```

[bazelproject.zip](https://github.com/gitbito/bitoai/files/14804989/bazelproject.zip)

**Comment by Algomorph** [comment] 2024-03-29 14:01
Indexing seems to complete fine after the project sync, but I'm also seeing "Size calculation in progress...", which never actually gets replaced by a true size.
![image](https://github.com/gitbito/bitoai/assets/1050606/84bac1ba-015e-4a34-a513-bfd641787b07)

**Comment by nisha-bito** [comment] 2024-04-02 05:23
hi @Algomorph ,

Can you please share the idea.logs file. 
Also can you share the .bitoignore and .gitignore files also to further analyse the issue? 

Thanks,
Nisha

**Comment by nisha-bito** [comment] 2024-04-04 08:28
hi @Algomorph ,

Based on the information provided and screenshot's, we analysed the issue. Please find the cause of the indexing failure -
1. We see that you are using a plugin `Bazel (build and test tool)` plugin in CLion.
2. Bazel Plugin creates a `.clwb` directory (a configuration directory created by Bazel). This directory is responsible for resetting the current project path to its location. e.g. if your project actual path is `/home/user/testProjects/mediapipe`. because of Bazel the project directory became "`/home/user/testProjects/mediapipe/.clwb`".
3. As the `.clwb` directory itself is a `.`(dot) directory, BITO plugin ignores this directory to read and hence the size of the project is 0 (zero) and the UI shows `Size Calculation In Progress`.

**Possible workaround -** 
1. Please disable Bazel tool.
2. Install Bito, check project path is /home/user/testProjects/mediapipe and not /home/user/testProjects/mediapipe/.clwb
3. Index the project. 
4. And then re-enable/install Bazel tool.

**Drawback of the workaround -** 
1. Bito keeps re-indexing the directory for any changes done in your local code base. 
2. However with above workaround, re-indexing will fail [due the same project path issues] and for doing re-index also, the workaround to be done. 

More information on the indexing can be found here - https://docs.bito.ai/feature-guides/ai-that-understands-your-code

Please let us know if this workaround works for you. We will work on a possible fix from our side, however it will take some time to release the fix. 

Thanks,
Nisha

**Comment by nisha-bito** [comment] 2024-04-08 07:53
hi @Algomorph ,

Please suggest, if the workaround suggest is working for you. 
Also let us know if we can close this issue? 

Thanks,
Nisha

**Comment by Algomorph** [comment] 2024-04-08 12:20
@nisha-bito , I will try the workaround as soon as I get a chance. The issue should only be closed when you come up with a fix, not a workaround.

**Comment by Algomorph** [comment] 2024-04-08 15:55
@nisha-bito , the workaround you propose doesn't quite work, but there is an alternative workaround that _kinda_ works
![image](https://github.com/gitbito/bitoai/assets/1050606/144e3913-3775-48bd-8fd8-827cf25624c8).

Most importantly, I have to reload the ".clwb" project in order for the Bazel plugin to kick in, otherwise I can't use Bazel to build/run/debug/analyze the project. 

Now, if, instead, I open the `mediapipe` project (as opposed to `mediapipe/.clwb` Bazel project) in a separate window, the query kinda works, although returning a completely bogus, useless answer. It includes only one header out of the many that are actually in that folder ([session link](https://share.bito.ai/static/share?aid=a3fd6ff5-9d5c-408e-b0bc-a2f6691ce80e)).

Context about my user story: I have no choice but to use Bazel at my work right now due to the way the system was built before I came on board. Bazel is an alternative build system to CMake, and I'm less familiar with it than with CMake, so this is where I could really use some AI help. Ironically, it seems like BitoAI has no support for it.

It also feels to me like the fix should be very simple:
(a) determine if the project opened is a Bazel project and
(b) if it is, index the parent directory instead of the project folder.

**Comment by nisha-bito** [comment] 2024-04-15 07:41
hi @Algomorph ,

Sorry to hear that work around is not working properly. We are already working on the fix and the fix shall be available in couple of days. 
I will confirm you when the new release is done with this fix. 

Thanks,
Nisha

**Comment by nisha-bito** [comment] 2024-05-02 08:15
hi @Algomorph ,

We have released the fix along with Bito 1.3.2 version. please let us know if this works for you. 

Thanks,
Nisha

**Comment by nisha-bito** [comment] 2024-05-09 09:39
hi @Algomorph ,

Please let us know if the fix is working fine for you. 
This ticket will be closed now, feel free to re-open it in case the fix is not working for you. 

Thanks,
Nisha

**Closed by nisha-bito** 2024-05-09 09:39 UTC

**Comment by Algomorph** [comment] 2024-05-10 13:03
@nisha-bito thanks, Bazel support does seem to work now. Utility has been very limited so far, but I will keep evaluating Bito.
